# Starship configuration file
# Configuration page: https://starship.rs/config/
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 2000
add_newline = false

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
